apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-bridge.fullname" . }}-config
  labels:
    {{- include "git-bridge.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
